<?php
/** @var \YuryCompany\Hobby\Block\Hobby $block */
?>
<div class="row">
    <div class="col-md-8">
        <form name="addData" method="post" id="addData" class="form"
              action="<?php echo $this->getFormAction(); ?>"
              data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <legend class="legend"><span><?= $block->escapeHtmlAttr(__('Fill Detail')) ?></span></legend>
                <fieldset class="fieldset row">
                    <div class="fields col-md-6">
                        <div class="field name">
                            <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Hobby')) ?></span></label>
                            <select id="hobby" name="hobby" title="Hobby">
                                <?php $options = $block->getHobbyOptions(); ?>
                                <?php $value = $block->getHobbyId(); ?>
                                <?php foreach ($options as $option) : ?>
                                    <option value="<?= $block->escapeHtmlAttr($option['value']) ?>"<?= ($option['value'] == $value) ? ' selected="selected"' : '' ?>><?= $block->escapeHtml(__($option['label']->getText())) ?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                    </div>
                </fieldset>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary" title="Save"><span><?= $block->escapeHtmlAttr(__('Save')) ?></span></button>
                </div>
            </div>
        </form>
    </div>
</div>
